# Generated by Django 4.1.6 on 2023-02-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='tag',
            field=models.CharField(default='tag', max_length=100),
        ),
    ]
