# Generated by Django 4.1.6 on 2023-02-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='tag',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
