# Generated by Django 4.1.6 on 2023-02-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_alter_fotografia_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='tag',
        ),
    ]
