# Generated by Django 4.1.6 on 2023-02-07 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
