# Generated by Django 4.1.6 on 2023-02-09 16:33

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0011_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotografia',
            options={'verbose_name': 'Fotografia', 'verbose_name_plural': 'Fotografias'},
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Nebulosa', 'NEBULOSA'), ('Estrela', 'ESTRELA'), ('Galáxia', 'GALÁXIA'), ('Planeta', 'PLANETA')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='fotos/%Y/%m/%d/', variations={'thumbnail': {'crop': True, 'height': 500, 'width': 500}}, verbose_name='Fotografia'),
        ),
    ]
